apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xylia-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: xylia.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xylia-service
            port:
              number: 80
